### PR TITLE
Deactivated the PlantUML self test part from GenPackageDoc

### PR DESCRIPTION
**Pull request by HolQue**

### CODE REVIEW

**Review by test-fullautomation — COMMENTED** [review]
Hi Holger,
as per Ngoan the test should pass without JAVA configuration as part of our installation.
Therefore I don't merge for the moment.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

??????????????????

PlantUML requires JAVA. Without JAVA available, the self test of GenPackageDoc will fail. That is the reason to deactivate the PlantUML test case from self test of GenPackageDoc in this pull request.

**Comment by test-fullautomation** [comment]
As per Ngoan the SelfTest machines configure JAVA already before our installer is executed.
Therefore it's not required to check for JAVA in this case.

**Comment by HolQue** [comment]
Hi Thomas,

please discard this pull request. Doesn't make sense any more.

**Pull request closed without merging**
